server:
  address: "127.0.0.1"
  port: 8080

github:
  v3_api_url: "https://api.github.com/"
  app:
    integration_id: 0
    webhook_secret: "very-secret"
    private_key: |
      68c8b1bf0e2eb852ab6575ead878d935af59487c