server:
  address: "0.0.0.0"
  port: 8080

expected_pusher_name: "azure-verified-module-draft[bot]"

github:
  v3_api_url: "https://api.github.com/"
  app:
    integration_id: 811509
    webhook_secret: ${webhook_secret}
    private_key: |
