name: Main Branch Push
on:
  push:
    branches:
      - main

permissions:
  issues: write
  pull-requests: write

jobs:
  main-branch-push:
    runs-on: [self-hosted, 1ES.Pool=avm-gh-app]
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2215326c76d51bfa3f2af0a470f32677f6c0cae9 # 2.2.0
        id: PR
      - name: checkout
        if: steps.PR.outputs.number != ''
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - name: Download pr tfplan
        if: steps.PR.outputs.number != ''
        run: |
          az login --identity --username $MSI_ID > /dev/null
          az storage blob download --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name telemetry/tfplan_${{steps.PR.outputs.number}} --no-progress --file tfplan --auth-mode login
      - uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 # 3.0.0
        if: steps.PR.outputs.number != ''
      - name: Apply
        if: steps.PR.outputs.number != ''
        env:
          GH_APP_PRIVATE_KEY_PEM: ${{ secrets.PRIVATE_KEY_PEM }}
          GH_APP_WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          GH_APP_INTEGRATION_ID: ${{ secrets.APP_INTEGRATION_ID }}
          BACKEND_STORAGE_ACCOUNT_NAME: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          BACKEND_RESOURCE_GROUP_NAME: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          BACKEND_CONTAINER_NAME: ${{ secrets.BACKEND_CONTAINER_NAME }}
          BACKEND_KEY: ${{ secrets.BACKEND_KEY }}
        run: |
          az login --identity --username $MSI_ID > /dev/null
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          export ARM_USE_MSI=true
          terraform init -backend-config="storage_account_name=$BACKEND_STORAGE_ACCOUNT_NAME" -backend-config="resource_group_name=$BACKEND_RESOURCE_GROUP_NAME" -backend-config="container_name=$BACKEND_CONTAINER_NAME" -backend-config="key=$BACKEND_KEY"
          terraform apply -auto-approve -input=false --compact-warnings tfplan
          terraform output
      - name: Delete tfplan file
        if: steps.PR.outputs.number != ''
        run: |
          az storage blob delete --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name avmghapp/tfplan_${{steps.PR.outputs.number}} --auth-mode login
          az storage blob delete --account-name tfmod1espoolstatestorage --container-name azure-verified-tfmod-pull-request-plans --name avmghapp/tfplan_${{steps.PR.outputs.number}}.txt --auth-mode login
      - name: PR comment with reactions
        if: steps.PR.outputs.number != ''
        uses: thollander/actions-comment-pull-request@8a3fad13c20088e9eb0805666b9fe49509d2fec8 # 1.6.0
        with:
          message: |
            tfplan file applied and purged ! :wave:
          reactions: rocket
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ steps.PR.outputs.number }}